services:
  
  db:
    container_name: auth_db
    image: postgres:14-alpine
    env_file:
      - ./token_service/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    networks:
      - app-network

  auth-service:
    container_name: auth_service
    build:
      context: ./token_service
      dockerfile: Dockerfile
    environment:
      CONFIG_PATH: .env
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - app-network


volumes:
  db_data:


networks:
  app-network:
